region: eu-west-1

function_name: efs_cw_lambda_function
handler: service.handler
description: Lambda function to update the SizeInBytes EFS CloudWatch metric 
runtime: python2.7
role: lambda_basic_execution

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
# bucket_name: 'example-bucket'
# s3_key_prefix: 'path/to/file/'

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 60
# memory_size: 512
#

# Experimental Environment variables
environment_variables:
    filesystem_id: fs-d617b81f
    region: eu-west-1

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
